title: Kittipon Rakwong
#logo: /assets/img/filename.png
#description: text below image
#show_downloads: true
theme: jekyll-theme-architect
# theme: architect, cayman, dinky, hacker, leap-day, merlot, midnight, minima, minimal, modernist, slate, tactile, time machine
